class task{
    constructor(
        id,
        partner_id,
        consultancy_agency_id,
        member_id,
        admin_id,
        applied_id,
        description,
        required_skills,
        monetary_compensation,
        deadline,
        deadline_for_apply,
        upload_date,
        submission_date,
        experience_level,
        commit_level,
        work_cycle,
        link_of_task,
        user_rate,
        accepted,
        rate,
        consulty_needed,
        cunsulties_done)
        {
                this.id=id;
                this.partner_id=partner_id;
                this.consultancy_agency_id=consultancy_agency_id;
                this.member_id=member_id;
                this.admin_id=admin_id;
                this.applied_id=applied_id;
                this.description=description;
                this.required_skills=required_skills;
                this.monetary_compensation=monetary_compensation;
                this.deadline=deadline;
                this.deadline_for_apply=deadline_for_apply;
                this.upload_date=upload_date;
                this.submission_date=submission_date;
                this.experience_level=experience_level;
                this.commit_level=commit_level;
                this.work_cycle=work_cycle;
                this.link_of_task=link_of_task;
                this.user_rate=user_rate;
                this.accepted=accepted;
                this.rate=rate;
                this.consulty_needed=consulty_needed;
                this.cunsulties_done=cunsulties_done;}
        };

        module.exports = task